### ISSUE TITLE
window buttons absent

### ISSUE THREAD

**Issue by Rathod-Sahaab** [B00merang-Project/macOS-Dark#10]
window buttons are absent on maximum windows except for **terminal emulator** and **nautilus**
![screenshot from 2019-01-06 23-04-29](https://user-images.githubusercontent.com/31929374/50739508-9d9e9e80-1207-11e9-8afe-08e60810704c.png)
what I changed in theme

1. Removed apple's logo just commented out the background image(activities Menu)
2. Changed folder's name from MacOS-Dark-master  to MacOS Dark Knight
Loaded fine in gnome tweaks

--USING--
Ubuntu18.04 gnome
--Edit--
changed from communitheme from login screen to ubuntu on x11 and work well now

**Comment by Elbullazul** [comment]
so everything's OK now?

**Comment by Rathod-Sahaab** [comment]
Yep, just bit of concern for communitheme Ubuntu
