### ISSUE TITLE
Metacity theme doesnt work

### ISSUE THREAD

**Issue by joshuah345** [B00merang-Project/macOS-Dark#11]
i currently am running mate-desktop and putting the themes in the folder makes them show up, but applying them doesnt work (question mark on theme image)

**Comment by Elbullazul** [comment]
the metacity theme doesn't work because mate desktop is using metacity-2 themes now, and it's not yet implemented in this theme. you could try renaming macOS/metacity-1/metacity-3.xml to metacity-2.xml but i'm not shure it will work
