### ISSUE TITLE
On Mint Cinnamon, titlebar text seems uncentered

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [B00merang-Project/macOS-Dark#12]
Screenshot: 
![image](https://user-images.githubusercontent.com/47056543/52181771-9c07cc80-27ed-11e9-8023-e301b1f5aa06.png)

Mint 19.1 x64 Cinnamon
Theme version: latest git.

**Comment by LinuxOnTheDesktop** [comment]
And, using, in addition to the window border theme,  the 'controls' theme, there's some stuff I am not sure about . .

![image](https://user-images.githubusercontent.com/47056543/52181809-12a4ca00-27ee-11e9-827a-55cfb9cc6bfd.png)

See especially the incomplete rectangle around one the Nemo icons.

**Comment by Elbullazul** [comment]
I'm currently rewriting some modules of the theme, so this should be fixed in the next release

**Comment by LinuxOnTheDesktop** [comment]
Jolly good.

**Comment by Elbullazul** [comment]
fixed on mint 19.1 with metacity-3.xml theme

**Comment by LinuxOnTheDesktop** [comment]
I downloaded the lastest version just now via git. The titlebar text is still off-centre, sadly. Also, Firefox, which I have set to use my system borders (not to draw tabs in the titlebar) has ended up entirely without window buttons!

Mint 19.1 Cinnamon.

**Comment by Elbullazul** [comment]
can you post a screenshot? I'm pretty shure on my install it's centerd. That button issue is weird, can you submit a screenshot of that also?

**Comment by Elbullazul** [comment]
![image](https://user-images.githubusercontent.com/15310985/55724503-8f644800-59d9-11e9-9812-1c6a3c40535f.png)

f36bfb9 completely fixes this
