### ISSUE TITLE
Isuses with MacOS-Dark Xfwm theme and panel in xfce.

### ISSUE THREAD

**Issue by freefreeno** [B00merang-Project/macOS-Dark#13]
1. Slider buttons in settings need to be a different color than black.
2.Opacity shouldn't be set in themerc file.
3. Windows try to pop up in corners after I change them to center over and over.
4.If you are gonna take the control way from xfce users about buttons at least give them guidance for a 
   new thermerc file to set if they want it the old way with buttons on right and controls working in settings.
5. The xfwm4 theme buttons are blurry in the colors.
6. The pulse audio button and whisker menu buttons are wrong color. There is a screen with another mac theme with clear buttons right below. it is the first one with title of different buttons.
![screenshot_of_different_buttons](https://user-images.githubusercontent.com/41884680/52303559-f02dc080-2955-11e9-917b-a403d37a4a5c.png)

![screenshot_2019-02-05_14-40-09](https://user-images.githubusercontent.com/41884680/52303223-02f3c580-2955-11e9-84ce-c9252da503b0.png)

![screenshot_2019-02-05_14-29-55](https://user-images.githubusercontent.com/41884680/52303116-c0ca8400-2954-11e9-879b-3897aa13b687.png)

![screenshot_2019-02-05_14-29-24](https://user-images.githubusercontent.com/41884680/52303677-3a16a680-2956-11e9-9bff-3c3667e37988.png)

**Comment by Elbullazul** [comment]
> - [x] Slider buttons in settings need to be a different color than black. **(fixed in b9801eb)**
> - [x] Opacity shouldn't be set in themerc file. **(fixed in 98e0ddf)**
> - [ ] Windows try to pop up in corners after I change them to center over and over.
> - [x] If you are gonna take the control way from xfce users about buttons at least give them guidance for a new thermerc file to set if they want it the old way with buttons on right and controls working in settings. **(fixed in 98e0ddf)**
> - [x] The xfwm4 theme buttons are blurry in the colors. **(fixed in 98e0ddf)**
> - [ ] The pulse audio button and whisker menu buttons are wrong color. There is a screen with another mac theme with clear buttons right below. it is the first one with title of different buttons.

please note that some controls may also appear blurred. It's the GTK2 theme, I need to rollback to the murrine engine, the pixbuf variant has been really disappointing

**Comment by Elbullazul** [comment]
all issues have been fixed
