### ISSUE TITLE
All the problems with MacOS-Dark theme outlined in one article.

### ISSUE THREAD

**Issue by freefreeno** [B00merang-Project/macOS-Dark#15]
I did it this way because I had messed up the other when telling you these problems but instead of opening a new issue I edited the old one but I don't think that was correct either because you don't see it as a new issue. Well here it is all laid out with as clear as understanding as you will get. Just click the link and look at that issue. It is edited from other day.
https://github.com/B00merang-Project/macOS-Dark/issues/14#issuecomment-465212463

**Comment by Elbullazul** [comment]
will have a look, thanks
