### ISSUE TITLE
Search bar in thunar. ( Observation)

### ISSUE THREAD

**Issue by freefreeno** [B00merang-Project/macOS-Dark#16]
1.The outline only glows around the thunar search bar when it is clicked inside of so pretty much never. It looks great when it is lit up so light that baby up all the time or add maybe a less lit up glow to the search bar for normal use and let the more bright glow come on for when it is clicked. Another idea is add an regular outline of some sort to the search bar and let the other be for when you have it clicked inside of it but I don't know if I or anyone else is ever gonna see that beautiful blue glow in thunar because I don't think many people ever type inside that search bar. I know I never do. I DO NOT KNOW HOW IT WOULD LOOK LIKE THIS BECAUSE I AM NOT GOOD ENOUGH TO CHANGE THIS INSIDE THE CONFIGS. ( 2.) I have noticed a weird line about straight down the middle if the header bars for regular style gnome apps.There is the search icon built into the header bar and well about middle ways of the circle in the search icon there is what looks like an edge a color that doesn't blend or something and it runs all the way across the header bar on all regular style gtk apps  like these.
![screenshot_2019-03-01_10-32-27](https://user-images.githubusercontent.com/41884680/53652150-c6428380-3c0d-11e9-8ddf-c99717fbc372.png)

On this one the line or edge or whatever it is is about half down the box that says saved colors and goes downward for not very far and then all the way across the top bar.
![screenshot_2019-03-01_16-39-48](https://user-images.githubusercontent.com/41884680/53670535-ae382780-3c40-11e9-8167-4f07c237af13.png)

(3) Something that I think would be a great addition is a .xml text editor theme with the same background color black as the base color of your theme. I have plenty but they all change the background of the theme to a different black and I like your black so pretty much I don't like them anymore but if we had a couple for your theme then this would also set your theme apart from others as well. Here is one I got from the gtk website called vsdark and it has blue in it with a dark background but it does change the black background also so if it just was changes to match the black in your base color then it would look great. Just change the background to your black and change txt to xml. These can be put in  usr/share/gtksourceview-3.0/styles/ or .local/share/gtksourceview-3.0/styles/

[vsdark.txt](https://github.com/B00merang-Project/macOS-Dark/files/2920854/vsdark.txt)

The chrome theme is very nice by the way. Also everything else is looking pretty really good and clean.
I am on gtk 3.24.5.
![screenshot_2019-03-01_22-45-10](https://user-images.githubusercontent.com/41884680/53677380-85ca2080-3c74-11e9-88fd-40e61add5cf9.png)

![screenshot_2019-03-01_14-37-11](https://user-images.githubusercontent.com/41884680/53664973-c2bff400-3c2f-11e9-8af9-6a15f75c6ab6.png)

![screenshot_2019-03-01_22-12-35](https://user-images.githubusercontent.com/41884680/53677091-0e928d80-3c70-11e9-943c-824d26995491.png)

![screenshot_2019-03-01_22-23-30](https://user-images.githubusercontent.com/41884680/53677146-f0795d00-3c70-11e9-8e95-3ac21123949d.png)
The more I use this theme the more I love it and I am telling you the performance is very good with this theme compared to the others I have been using. More snappy.

**Comment by Elbullazul** [comment]
what editor is it that you want a dark theme for? by the name of the file I'm guessing Visual Studio code?
the headerbar gradient seems odd indeed. However, it's weird because GTK is supposed to smooth out the colors I give it, but it doesn't appear to do a good job. I'll try to see if it can be reworked.

The searchbar shadow is setup to work as it does on macOS, which only highlights it when focused. If you want it always on I can send you a patched version.

it's funny you mention performance since I use a custom slimmed down codebase for my themes.

BTW which icon theme do you use? It looks super good

**Comment by freefreeno** [comment]
That is the Korla icon theme and I love it also because of the blue folders. It is not that light blue some use for MAC like folders. Looks great with your theme. Here it is.

git clone https://github.com/bikass/korla.git

That will give you both versions light and dark. Light is still in beta but it works good also. I am just talking about colored syntax themes for text editor and that is just the VSDark .xml theme for plain ole mousepad. I shared it up top in txt format and all you need to is click on it and download it and change extension to .xml and put in the one of the locations up top and it will work with gedit and mousepad I know for sure. I downloaded it from the GTK website. The blue matches my folders and your theme pretty good I think. I will not bother you over the search bar glow but while I am here I love your xfwm4 theme and to tell you the truth I use it on a whole bunch of other themes but of course it doesn't match them perfectly but it blends in pretty good.I even use it on Adwaita theme. I like how it sets low and that it blends into the theme and not stuck out like a sore thumb. I can not for the life of me figure out how to change its color to match my other themes. If I had it in an assets.svg with a little script like render-assets.sh then I believe I could change its color in the assets.svg form with Inkscape and then render the assets and I would be able to use it on all my themes. I would give anything to be able to do what you do and I will learn to do it if it is the last thing I ever do. For over a month I have been studying themes and how css and sass work and also meson but to be honest I am a self taught Arch Linux guy and I don't know if I will ever be able to learn it without some teaching ya know. Everything and I do mean everything I know I have taught myself. I have a good eye for what looks good but I can't translate that to code and it is so so aggravating. I am not a dumb person but it is a lot to learn without any real teaching in code of any kind. I refuse to give up though. But yea there is the icons and if you would please give me hint on how to change the colors in the xfwm4 theme so I can use it on all my theme.  Thanks for your work. Really.

**Comment by Elbullazul** [comment]
the xfwm4 as an svg render is an interesting idea. I haven't worked with that before but I guess it would be pretty easy to implement (also it would work well for me to adapt other OS X xfwm themes)

if you're interested I can write a quick guide to GTK theming with CSS/SASS.

**Comment by freefreeno** [comment]
Most if not all the themes I am using these days IF you download them from github as all one big package then they are including the sass and scss files and stuff and they are doing there xfwm4 like that I have shown up top. My problem with changing the colors of your xfwm4 is they are mostly .xmp files and I have NO IDEA how to change the color without ruining the the fade in the colors. It ends up being like a sold color all the way through and looks as though it is just a xfwm4 with one flat color and it ruins it. YES I would truly enjoy a guide and I would put it to good use. I have a passion for this but don't have a clue where to start really.

**Comment by freefreeno** [comment]
Right now I am trying to match the xfwm4 to this theme which looks great in xfce. I don't want you to think I am not using your theme because I am but I have a few I would like to adapt your xfwm4 theme to like this.
It would need to be.
#353839
![screenshot_2019-03-03_12-43-10](https://user-images.githubusercontent.com/41884680/53699818-f7f44f80-3db1-11e9-85fc-3c53bd6a191a.png)
 
Another thing while I am here is this look how the black comes all the way up on this one.
![screenshot_2019-03-03_12-34-27](https://user-images.githubusercontent.com/41884680/53699842-15291e00-3db2-11e9-8f7f-f73658cc8bda.png)

This is yours so you decide I guess but I am liking the all the way up with the black.
![screenshot_2019-03-03_12-47-26](https://user-images.githubusercontent.com/41884680/53699894-92549300-3db2-11e9-813c-ee49d682cdcd.png)

**Comment by freefreeno** [comment]
The xfwm4 does NOT end up as a svg. It starts in a grouped svg and ends up as ungrouped png's if you run the render assets script that i showed you. You change the color of the grouped svg and then render assets and the assets being the files in the xfwm4 folder. Copy the themerc file to that folder and done. You will have the same svg file for later color changes for the future. I don't know if you can see it above where the black runs all the way up but there is line little line dividers there. It isnt jut black all the way without a break up point. Here is a better example you can see.

![screenshot_2019-03-04_13-00-21](https://user-images.githubusercontent.com/41884680/53755966-897cc380-3e7d-11e9-9f15-ef45b550972e.png)
