### ISSUE TITLE
Search bar in nautilus and the search bars are too flat.

### ISSUE THREAD

**Issue by freefreeno** [B00merang-Project/macOS-Dark#19]
Top bars in new install of Arch gnome. They just don't look coorect and the selected_bg is not showing.
![Screenshot from 2019-03-14 19-54-22](https://user-images.githubusercontent.com/41884680/54400926-3a137000-4693-11e9-9946-3d839a00294c.png)

They are too flat.

![Screenshot from 2019-03-14 19-58-42](https://user-images.githubusercontent.com/41884680/54400998-9f676100-4693-11e9-8e05-8325a6fd3874.png)

That one shows how flat the title bar are but they are all like that.
And maybe offer a version without the transparency in side bar. Performance is great but for gnome just need a little tweaking.

**Comment by Elbullazul** [comment]
no transparency sidebar: open gtk.css, and replace `alpha(@bg_color)` with `@bg_color`

I'll try to have something worked out for the headerbar gradients

**Comment by freefreeno** [comment]
I moved to KDE and I only regret I didn't do it from the beginning. Man in the past year to 2 years they have made strides in KDE. I am in awe this operating system. It may take a lot of tweaking to get it where you want it but all in all it is hands down best Linux distro and you can directly edit themes.  More features then all the rest of the distro's put together. Thanks for your work.

**Comment by Elbullazul** [comment]
I just checked the titlebar gradients in original macOS are just as "flat" (you see color variations only when fetching the HEX values in GIMP), so I think it looks OK.

the shadow is a bug because the overall layout of entries isn't made for outset shadows.

hope you find joy in KDE, you're the 3rd already to do so ;)
