### ISSUE TITLE
Chromium download bar color

### ISSUE THREAD

**Issue by JulyanoF** [B00merang-Project/macOS-Dark#20]
My Chromium download bar background is white and font color too, how can I fix it?

<img src="https://i.postimg.cc/qqhx6jbX/image.png" />

**Comment by Elbullazul** [comment]
will check, I don't have the latest version installed and last try I gave at updating the VM everything broke, so this may take some time

**Comment by freefreeno** [comment]
This has been like this for me on every single theme over three different Linux operating systems since latest chrome update so they changed something.

**Comment by JulyanoF** [comment]
@Elbullazul @freefreeno I found a "solution", maybe themporary:

```
cp /usr/share/applications/chromium-browser.desktop ~/.local/share/applications

perl -i -pe 's/(Exec=chromium-browser)/$1 --enable-features=WebUIDarkMode --force-dark-mode/g' ~/.local/share/applications/chromium-browser.desktop
```

**Comment by Elbullazul** [comment]
seems it has been fixed upstream
