### ISSUE TITLE
Sharper icons?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [B00merang-Project/macOS-Dark#21]
Here is how the icons - the window decorations - look on my Mint computer (screen size 14"; screen resolution 2560x1440; HiDPI; ).

![image](https://user-images.githubusercontent.com/47056543/55725457-a751c100-5a05-11e9-9e62-a26b77e16e38.png)

Nice - and, now, centered (which is good) - but . . a little fuzzy, perhaps?

**Comment by Elbullazul** [comment]
wroking on it right now

**Comment by Elbullazul** [comment]
86f7c78 uses SVGs instead, should be better now

**Comment by LinuxOnTheDesktop** [comment]
That is an improvement. Fast and good work! Thank you.
