### ISSUE TITLE
Nautilus header issue

### ISSUE THREAD

**Issue by paulcarroty** [B00merang-Project/macOS-Dark#26]
![header](https://user-images.githubusercontent.com/1550705/87030002-a94a9700-c1e9-11ea-8302-df85e041e3dd.png)

Header delimiter and body delimiter are different.

**Comment by Elbullazul** [comment]
If you've changed the sidebar's size, it's expected. Is that the default width? If so, I'll change it

**Comment by paulcarroty** [comment]
It's 99% default width 'cause I never resized the sidebar. Thx.

**Comment by Elbullazul** [comment]
fixed
