### ISSUE TITLE
Title bars way too thick 

### ISSUE THREAD

**Issue by sreekaransrinath** [B00merang-Project/macOS-Dark#28]
![image](https://user-images.githubusercontent.com/50989977/102779052-9b648900-43b9-11eb-8c42-62b360d66dfb.png)

Thinner title bars would be far more appealing imo. These just look like the pixel 2 xl notch

**Comment by dominichayesferen** [comment]
_I mean, they're just like the source material (very thicc)._

**Comment by Elbullazul** [comment]
@sreekaransrinath has a point though. The macOS terminal has a slimmer titlebar, but it's because it doesn't have a "unified" titlebar like, say, Finder. Example:
![img](https://miro.medium.com/max/3200/0*ncMsAOAHG8DQaNFC)

I'd recommend using xfce4-terminal who uses a slimmer titlebar
