### ISSUE TITLE
Top/title bar in Files is off

### ISSUE THREAD

**Issue by jakobhansson** [B00merang-Project/macOS-Dark#29]
![Screenshot 2020-12-23 115805](https://user-images.githubusercontent.com/12063035/102989723-6457ba00-4516-11eb-8bf9-2b2cee1f5726.jpg)

**Comment by Elbullazul** [comment]
noted

**Comment by NikRADX1905** [comment]
I also have the same problem,  back and forward button are with title bar control buttons

**Comment by Elbullazul** [comment]
d9c37f5 fixes this
