### ISSUE TITLE
Virtual keyboard does not show the letters on the keys

### ISSUE THREAD

**Issue by haggen88** [B00merang-Project/macOS-Dark#31]
@B00merang-Project

![macOS-Dark6 1-dark](https://github.com/B00merang-Project/macOS-Dark/assets/68134588/5b33eee2-9059-4a0e-b424-0e1ba2b8d431)

Linux Mint (21.3) Cinnamon
system font : Inter regular - size: 10

**Comment by Elbullazul** [comment]
I'll have a look at this later today, thanks for your bug report.

**Comment by haggen88** [comment]
Thank you for your response. Otherwise, the virtual keyboard package is called libcaribou.

**Comment by Elbullazul** [comment]
strange, it displays them correctly on my end:
[6876a22](https://github.com/B00merang-Project/B00merang-Blackout/commit/6876a2215120e3225282c7e1249a8ab2d8f8a435)

can you post the following info?
- linux distro and version
- cinnamon version
- display resolution
- link to where you downloaded the theme, if possible

**Comment by haggen88** [comment]
Linux distro: Linux Mint 21.3
Cinnamon: 6.0.4
Display resolution: 1366x768
If I remember correctly, I downloaded it from Pling/Opendesktop (as macOS-6.1 / macOS-Dark-6.1-dark).  
EDIT:  I recently found the [link](https://www.opendesktop.org/p/1405530)

My theme configuration:
![config](https://github.com/user-attachments/assets/86f3b3a6-8372-4e8d-9aaf-8eebb9766371)

virtual keyboard config: 
![vk conf](https://github.com/user-attachments/assets/d619b6bb-cef1-4162-b650-d1ba690154ae)

**Comment by Elbullazul** [comment]
fixed in [85f6339](https://github.com/B00merang-Project/macOS-Dark/commit/85f6339b864d40299c2a250131ae56b3940cb59f)
