### ISSUE TITLE
[Budgie] desktop panel overflows + Has no dark theme

### ISSUE THREAD

**Issue by devxpy** [B00merang-Project/macOS-Dark#7]
```
⋊ ~> budgie-desktop --version
budgie-desktop v10.4-85-g36667bcb
Copyright © 2014-2017 Budgie Desktop Developers
```

Screenshot 

![image](https://user-images.githubusercontent.com/19492893/41717302-ef70590c-7576-11e8-9e74-1b2514d03f47.png)

**Comment by Elbullazul** [comment]
doesn't happen on latest budgie and latest code from master
